export enum ProjectStage {
  IDEA = 'IDEA',
  DRAFTING = 'DRAFTING',
  READY = 'READY',
  SUBMITTED = 'SUBMITTED'
}

export interface Project {
  id: string;
  title: string;
  description: string; // The "1-pager" generated by AI
  stage: ProjectStage;
  documents: ProjectDocument[];
  matchedFunds?: FundMatch[];
}

export interface ProjectDocument {
  id: string;
  name: string;
  type: 'required' | 'optional';
  status: 'missing' | 'uploaded' | 'verified';
  file?: File;
}

export interface Fund {
  id: string;
  code: string; // e.g., "1501", "1507"
  name: string;
  institution: 'TUBITAK' | 'KOSGEB' | 'EU';
  description: string;
  maxBudget: string;
  supportRate: string;
}

export interface FundMatch {
  fundId: string;
  score: number; // 0-100
  rationale: string;
  eligibilityStatus: 'eligible' | 'conditional' | 'ineligible';
}

export interface IncorporationStep {
  id: string;
  title: string;
  description: string;
  completed: boolean;
  dueDate?: string;
  category: 'legal' | 'tax' | 'compliance';
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}
